# Generated by Django 2.0.4 on 2018-04-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.TextField()),
                ('short_url_path', models.CharField(max_length=7)),
            ],
        ),
    ]
